### ISSUE TITLE
Failed to set GPU settings

### ISSUE THREAD

**Issue by gamer01** [kitsunyan/intel-undervolt#1]
First: Thank you a lot for the work. i love the tool.

But:
I cannot set any value apart from the CPU voltage:
```
> sudo intel-undervolt apply
CPU (0): -70.31 mV
Failed to write value for GPU (1)
Failed to write value for CPU Cache (2)
Failed to write value for System Agent (3)
Failed to write value for Analog I/O (4)
```
When looking into your source i see, that you are calling the tools: `ioutils` and `regval`
Are those dependencies? Do you know where i can install them on archlinux?

**Comment by kitsunyan** [comment]
Which CPU do you have? I think it's possible that your CPU supports only `0` index. At least I know that some CPUs allow to configure more indices, but I can use only 0-4 on my CPU. Trying to set `5` index leads to the same error as in your output.

`ioutils` is a helper tool, it's installed to `/usr/lib/intel-undervolt/ioutils`.

**Comment by gamer01** [comment]
Intel i5-4330M

**Comment by gamer01** [comment]
I think its a bug nevertheless because when i use the commands like [here](https://github.com/mihic/linux-intel-undervolt#setting-the-voltages) it seems to work:
´´´
> sudo wrmsr 0x150 0x80000211ecc00000
> sudo intel-undervolt read          
CPU (0): -70.31 mV
GPU (1): -0.00 mV
CPU Cache (2): -150.39 mV
System Agent (3): -0.00 mV
Analog I/O (4): -0.00 mV
´´´

**Comment by kitsunyan** [comment]
Yes, that's definitely a bug then.

What happens if you try to use `ioutils` utility? `# /usr/lib/intel-undervolt/ioutils msr 0x150 0x80000211ecc00000`. (Use `# /usr/lib/intel-undervolt/ioutils msr 0x150` to read the value).

**Comment by gamer01** [comment]
```
> /usr/lib/intel-undervolt/ioutils msr 0x150 0x80000211ecc00000
> /usr/lib/intel-undervolt/ioutils msr 0x150
0x0000020000000000
```
Let me know if i can assist you in any way for debugging.

**Comment by kitsunyan** [comment]
Actually, if you want to read the value, you should write `0x8000021000000000` first.

```
# /usr/lib/intel-undervolt/ioutils msr 0x150 0x80000211ecc00000
# /usr/lib/intel-undervolt/ioutils msr 0x150 0x8000021000000000
# /usr/lib/intel-undervolt/ioutils msr 0x150
```

**Comment by gamer01** [comment]
Ah, read mode... :D
```
/usr/lib/intel-undervolt/ioutils msr 0x150 0x80000211ecc00000
> /usr/lib/intel-undervolt/ioutils msr 0x150 0x8000021000000000
> /usr/lib/intel-undervolt/ioutils msr 0x150
0x00000200ecc00000
```

**Comment by kitsunyan** [comment]
Oh, so it seems that it provides the index after reading. That explains the error.

```diff
--- a/intel-undervolt.in
+++ b/intel-undervolt.in
@@ -88,7 +88,7 @@ function handle-apply() {
 
   function tomv() {
     awk '{ printf("%0.2f", and(lshift(1, 32) - rshift(strtonum($1), 21),
-    0x7ff) / 1.024) }' <<< "$1"
+    0x7ff) / 1.024) }' <<< "0x${1: -8}"
   }
 
   for i in `seq 0 $((${#indices[@]} - 1))`; do
@@ -102,7 +102,7 @@ function handle-apply() {
       code="$?"
 
       [ "$code" = '0' ] && {
-        [ "$value" = "${values[$i]}" ] ||
+        [ "${value: -8}" = "${values[$i]: -8}" ] ||
         code='1'
       }
       true
```

Does this fix the problem?

**Comment by gamer01** [comment]
```
> sudo intel-undervolt apply
CPU (0): -70.31 mV
GPU (1): -105.47 mV
CPU Cache (2): -110.35 mV
System Agent (3): -0.00 mV
Analog I/O (4): -0.00 mV

Success
```
:+1:

**Comment by kitsunyan** [comment]
Fixed! https://github.com/kitsunyan/intel-undervolt/commit/ffacb8d6d09b51b960a39aa884f0153be495524a
