### ISSUE TITLE
how to disable short term package power max

### ISSUE THREAD

**Issue by gatalon** [kitsunyan/intel-undervolt#16]
I want to disable short term package power max, because I found that my cpu is more efficient with this function disable. i have tested with XTU on windows.
I am not sure if you can help to add this function. 
Your hardwork is very good and help for me by the way.

**Comment by kitsunyan** [comment]
This feature wasn't available, but I think it's a good idea to add it. Now you can add `:disabled` suffix to the power limit, check the example configuration!
