### ISSUE TITLE
Operation not permitted

### ISSUE THREAD

**Issue by gary094** [kitsunyan/intel-undervolt#17]
Hello there,

Installing went fine, issue is that I can't issue these commands:
`sudo intel-undervolt read` or `sudo intel-undervolt apply`

They both give me this as response:

`CPU (0): Operation not permitted`
`GPU (1): Operation not permitted`
`CPU Cache (2): Operation not permitted`
`System Agent (3): Operation not permitted`
`Analog I/O (4): Operation not permitted`

Altough `sudo intel-undervolt measure` is just fine.
Secureboot is disabled.
CPU: i7-4710HQ

**Comment by precla** [comment]
Hi, what distro and kernel version are you using?

Is Intel secure boot disabled?
Check if `msr-tools` is installed (not sure if you need this, but I'm atm nit at my notebook to check if I have installed it).
Run `lsmod | grep msr` to see if it's enabled.
To enable or temporarily run `modprobe msr`.

**Comment by gary094** [comment]
I am running Linux Mint 19.1 Kernel 4.15.0-45-generic x86_64

`lsmod | grep msr`
`msr                    16384  0`

`modprobe msr`
does not give me any output.

Just checked again, Secureboot is disabled. I have a slight suspicion that [this issue](https://github.com/tiziw/iuvolt/issues/11) might be somewhat related.

Throttlestop was working perfectly fine on Windows 10 if that helps.

Thanks for your help!

**Comment by precla** [comment]
Hm, I get the same output for `lsmod | grep msr`...
I'm not that good for that low level stuff so i can't help you more.
Only thing that i can suggest is to recompile the msr module as the it was mentioned in that issue:
https://github.com/intel/intel-cmt-cat/wiki/UEFI-Secure-Boot-Compatibility

**Comment by kitsunyan** [comment]
`measure` doesn't use MSR to measure power consumption, CPU speed, and sensors, so it isn't surprising it works. It should work even without root privileges.

However, I have no idea why it doesn't work for you even when secure boot is disabled. The issue you linked is about enabled secure boot, which is not your case.

It's interesting that it worked on Windows. Just out of curiosity, can you run `wrmsr 0x150 0x80000011ffe00000`?

**Comment by makarov-roman** [comment]
disabling secure boot works for me
check if secure boot is enabled by
```
mokutil --sb-state
```

**Comment by gary094** [comment]
Okay I triple checked and SecureBoot still is disabled BUT I had to delete some SecureBoot Variables in BIOS and now mokutil says:

`SecureBoot disabled
Platform is in Setup Mode`

Should be fine now I guess.
