### ISSUE TITLE
Raising the temperature limit

### ISSUE THREAD

**Issue by mvdan** [kitsunyan/intel-undervolt#18]
Thanks for the useful piece of software! I've been using it for a few months on my 6th gen x1 carbon.

It works well for my undervolting and power limit needs. However, this generation of Lenovo laptops has an issue on Linux; the temperature limit is hard-coded to 80C, while it's on 100C on Windows. See https://www.reddit.com/r/thinkpad/comments/870u0a/t480s_linux_throttling_bug/ for more information.

This project has a way to subtract a number from the initial temperature limit, such as going from 100 to 90 or 80. Could the reverse be implemented, so I could go from 80 to 90 or 100, and have my CPU throttle less? I've tried playing with the current settings, but I can't get the apparent limit to go past 80.

Thanks!

**Comment by kitsunyan** [comment]
`tjoffset` is substracted from the max temperature allowed for your CPU. If you can't get temperatures above 80°C, that means temperature offset is set to 20 by default. So you can reduce the offset (set it to -10 or even -3 depending on your fearlessness) and the temperature limit will be raised.
