### ISSUE TITLE
Problem with setting cpu tjunction offset

### ISSUE THREAD

**Issue by gamer01** [kitsunyan/intel-undervolt#2]
CPU: i5-4330M

when setting the tjunction limit, the apply script fails with the following error message:
```
 > sudo intel-undervolt apply          
CPU (0): -70.31 mV
GPU (1): -80.08 mV
CPU Cache (2): -70.31 mV
System Agent (3): -0.00 mV
Analog I/O (4): -0.00 mV

Failed to write MSR
Failed to write temperature offset value
```

when reading the value the script reports

**Comment by gamer01** [comment]
Yep, exactly :)

Does it help to test on a coffelake? today evening i could test if i can set higher values than 15 on my desktop.

**Comment by gamer01** [comment]
Maybe one small usability thing, for undervolting you take negative values for lowering, in tjoffset you take positive values for lowering. It was not too confusing for me, but it might confuse others and since this fooling around with temperature boundaries ist a little dangerous, one might want to be certain :)

**Comment by gamer01** [comment]
Interesting. maybe it makes sense to write those into the comments of the default config and when setting the value:
```
specified_new = min(specified, max_allowed(platform))
if (specified != specified_new)
  print info
```

**Comment by kitsunyan** [comment]
Yes, but identifying the platform and making such restrictions seems to be a difficult task. I'd like to just mention it in README.

**Comment by kitsunyan** [comment]
Fixed https://github.com/kitsunyan/intel-undervolt/commit/80f4061e66e0da4da0801486b6f3d07262d3364f https://github.com/kitsunyan/intel-undervolt/commit/9af42d09b9bd362518b3ee26d33a12e973d196b1
