### ISSUE TITLE
i3-3220 Input/output error

### ISSUE THREAD

**Issue by Massimo-B** [kitsunyan/intel-undervolt#24]
This is a 5.1.9 Kernel.
Modules are loaded:
```
# lsmod |grep rapl
intel_rapl             16384  0
intel_rapl_perf        12288  0
iosf_mbi               12288  2 intel_rapl,i915

```
intel-undervolt measure
works, but
Intel-undervolt read
returns Input/output error on all channels.

**Comment by stephanlachnit** [comment]
Your CPU is pre Haswell, so afaik it shouldn't work.
