### ISSUE TITLE
libelogind not found, cant install service, ubuntu 19.04

### ISSUE THREAD

**Issue by bosak** [kitsunyan/intel-undervolt#27]
Hi, On ubuntu 19.04,  after `./configure`, I got
```
Package libelogind was not found in the pkg-config search path.
Perhaps you should add the directory containing `libelogind.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libelogind' found
Enable systemd: false
Enable elogind: false
Enable OpenRC: false
```

So no systemd services are installed. Can you push me in right direction?

**Comment by kitsunyan** [comment]
Fixed configure script so it won't print these messages if you don't need elogind, for instance.

You need to pass `--enable-systemd` to configure script in order install systemd services. I updated the readme to mention this.
