### ISSUE TITLE
T490s - 50^C

### ISSUE THREAD

**Issue by alxchk** [kitsunyan/intel-undervolt#28]
For some reason after full load, CPU force frequency to ~1.2Ghz to keep 50^C. The only way to fix this - execute once https://github.com/erpalma/throttled.

Also tjunction is not applied after executing intel-undervolt apply. I.e. the value is the one from the config, but the actual temperature limit is not changed. Throttled somehow managed to change that

**Comment by kitsunyan** [comment]
Are you running intel-undervolt-loop service? Are you using thermald?

**Comment by alxchk** [comment]
No, I'm not using neither thermald not loop mode. Also when I started throttled, I let only to push values once, then ^C. Also, once happend, `intel-undervolt apply` does not change situation.

Also this strange situation happens without any obvious reason. I.e. I can compile something for half hour with full load and 80C, then do some break, then again, and then, in the middle of the process, this thing happen. 
First time it was immediately after I apply settings with tjoffset. But I can't reproduce this reliably this way. Maybe it is just coincidence.

What I can say for sure, for some reason real upper temperature does not change when using undervolt, but does in case of throttled.

Config for undervolt was:
```
undervolt 0 'CPU' -118
undervolt 1 'GPU' -90
undervolt 2 'CPU Cache' -118
undervolt 3 'System Agent' -50
undervolt 4 'Analog I/O' 0
tjoffset -15
daemon undervolt:once
daemon power
daemon tjoffset

```
This may be important. **This config does not include powerpackge hints**


The behavior happened with various values of these options, but anyway:

```
> cat /etc/tmpfiles.d/thermal_zone.conf 
w /sys/devices/platform/INT3400:00/uuids/current_uuid - - - - 63BE270F-1C11-48FD-A6F7-3AF253FF3E2D
```

```
cat /sys/devices/system/cpu/cpufreq/policy*/energy_performance_preference 
balance_performance
balance_performance
balance_performance
balance_performance
balance_performance
balance_performance
balance_performance
balance_performance
```

```
cat /sys/devices/system/cpu/cpufreq/policy*/scaling_governor 
powersave
powersave
powersave
powersave
powersave
powersave
powersave
powersave
```

```
> cat /sys/devices/system/cpu/intel_pstate/hwp_dynamic_boost 
0
> cat /sys/devices/system/cpu/intel_pstate/max_perf_pct 
100
> cat /sys/devices/system/cpu/intel_pstate/turbo_pct 
66
avatar > 
```

**Comment by kitsunyan** [comment]
Which throttled configuration do you have?

**Comment by alxchk** [comment]
Almost default:
```
[GENERAL]
Enabled: True
Sysfs_Power_Path: /sys/class/power_supply/AC*/online

[BATTERY]
Update_Rate_s: 30
PL1_Tdp_W: 29
PL1_Duration_s: 28
PL2_Tdp_W: 44
PL2_Duration_S: 0.002
Trip_Temp_C: 85
cTDP: 0

[AC]
Update_Rate_s: 5
PL1_Tdp_W: 44
PL1_Duration_s: 28
PL2_Tdp_W: 44
PL2_Duration_S: 0.002
Trip_Temp_C: 90
HWP_Mode: False
cTDP: 0

[UNDERVOLT.BATTERY]
CORE: -120
GPU: -25
CACHE: -120
UNCORE: -50
ANALOGIO: 0

[UNDERVOLT.AC]
CORE: -120
GPU: -25
CACHE: -120
UNCORE: -50
ANALOGIO: 0
```

**Comment by kitsunyan** [comment]
According to your config, throttled sets:

1. `MSR_TEMPERATURE_TARGET` (`0x1a2`), which is equal to `tjoffset` statement.
2. `MSR_CONFIG_TDP_CONTROL` (`0x64b`) to 0, there is no similar option in intel-undervolt and it's designed to adjust cTDP.
3. `MSR_PKG_POWER_LIMIT` (`0x610`) and `MCHBAR+0x59a0`, which is equal to `power package` statement.

So only 2 and 3 steps aren't performed by intel-undervolt according to your config, and that's the only difference. You can run throttled with `--debug` option to see the log.

> Also, once happend, intel-undervolt apply does not change situation.

Which output do you get after running this command? If it yields `-15`, then the value is definitely set correctly.

**Comment by alxchk** [comment]
Yes, -15 reads back. I'm trying now with config with power package. And now it does (at least from time to time) reach 85^C
