### ISSUE TITLE
intel-undervolt: command nod found

### ISSUE THREAD

**Issue by kilinochi** [kitsunyan/intel-undervolt#32]
how to add this command?

**Comment by delta-one** [comment]
How did you install it and what was the output ? Any errors ?

**Comment by kilinochi** [comment]
> How did you install it and what was the output ? Any errors ?

Okey, I understand


git clone https://github.com/kitsunyan/intel-undervolt
cd intel-undervolt/
./configure --enable-systemd --enable-openrc
make
sudo make install
sudo systemctl daemon-reload
