### ISSUE TITLE
[Question] What does the System Agent setting undervolt

### ISSUE THREAD

**Issue by XapaJIaMnu** [kitsunyan/intel-undervolt#40]
Hey,

Thank you for providing this tool. I'm currently experimenting with various settings, but I'm struggling to find details on what the  `System Agent` undervolts. Could you please clarify on what's happening?

Cheers

**Comment by regymm** [comment]
The Throttle Stop Q&A websites(like [here](https://linustechtips.com/main/topic/934392-throttlestop-what-does-this-stand-for-and-what-does-it-do/)) said that System Agent is something like memory controller and PCIe controller, which comsumes little power, and better leave untouched. I've slightly undervolted it and didn't see any difference(like power comsumption).

**Comment by kitsunyan** [comment]
System agent is a northbridge replacement integrated into CPU die. Sometimes it's also called "uncore".

There is [some mess](https://github.com/kitsunyan/intel-undervolt/issues/20) if you want to understand what actually this setting undervolts, though.
