### ISSUE TITLE
Package libelogind was not found in the pkg-config search path.

### ISSUE THREAD

**Issue by samimaftabahmed** [kitsunyan/intel-undervolt#47]
I have tried installing using the following command 
`sudo ./configure --enable-systemd --enable-elogind --enable-openrc`

but I am getting the following message

`Package libelogind was not found in the pkg-config search path.
Perhaps you should add the directory containing 'libelogind.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libelogind' found
Failed to configure eloginddir
`
My system has msr-tools installed and the CPU is Core i7-9750H on Ubuntu 18.04, kernel 4.18.20-041820-generic

**Comment by kitsunyan** [comment]
You need to enable elogind only if you use. On the most modern GNU/Linux systems `--enable-systemd` is enough.
