### ISSUE TITLE
Can't execute "systemctl enable --now intel-undervolt-loop.service"

### ISSUE THREAD

**Issue by TartanSpartan** [kitsunyan/intel-undervolt#52]
When I try to run `systemctl enable --now intel-undervolt-loop.service` it returns:

"Synchronizing state of intel-undervolt-loop.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable intel-undervolt-loop
update-rc.d: error: intel-undervolt-loop Default-Start contains no runlevels, aborting."

This seems to result in me being unable to use the service, so only the main command and daemon have any degree of persistence.

**Comment by kitsunyan** [comment]
Which `./configure` options did you use to install intel-undervolt?

**Comment by TartanSpartan** [comment]
When you said that I thought that may have been the issue, but I tried reinstalling using `./configure --enable-systemd` and the same error still gets thrown.

**Comment by kitsunyan** [comment]
I suppose you configured it with `--enable-openrc` the first time. In this case, if you already runned `make install`, there will be `/etc/init.d/intel-undervolt-loop` which can cause this conflict. Since there is no `uninstall` rule, can you try to delete `/usr/init.d/intel-undervolt-loop`?

To avoid such issues, try to use `checkinstall` tool next time (available on Debian and Ubuntu), it's much better to package tools than blindly run `make install`.

**Comment by TartanSpartan** [comment]
That sounds like a good suggestion and my bad if I included `--enable-openrc` the first time. I do see `/etc/init.d/intel-undervolt-loop`, but I don't see `/usr/init.d/`. Could there be a different explanation in this case?

**Comment by kitsunyan** [comment]
My bad, of course I meant `/etc`, not `/usr`.

**Comment by TartanSpartan** [comment]
Thanks for the correction, but it didn't fix the issue. However, I searched for the 'update-rc.d: error: intel-undervolt-loop Default-Start contains no runlevels, aborting' line and [this site](https://serverfault.com/questions/849507/systemctl-doesnt-recognize-my-service-default-start-contains-no-runlevels-abo) suggested including:

\### BEGIN INIT INFO
\# Provides:          my-service-name
\# Required-Start:    $all
\# Required-Stop:
\# Default-Start:     2 3 4 5
\# Default-Stop:
\# Short-Description: your description here
\### END INIT INFO

In the script, so I put that as a header in `/etc/init.d/intel-undervolt-loop` and that seems to fix the issue. However, it leads to the question as to why this header had to be manually added for me but (I presume) it's already in your machine's installation and for other users? If it helps, I'm running x86 Ubuntu 18.04.

**Comment by kitsunyan** [comment]
Tried to reproduce the issue, deleting the file helps:

```
$ sudo systemctl enable intel-undervolt-loop.service 
Synchronizing state of intel-undervolt-loop.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable intel-undervolt-loop
update-rc.d: error: intel-undervolt-loop Default-Start contains no runlevels, aborting.
$ sudo rm /etc/init.d/intel-undervolt-loop 
$ sudo systemctl enable intel-undervolt-loop.service 
Created symlink /etc/systemd/system/multi-user.target.wants/intel-undervolt-loop.service → /lib/systemd/system/intel-undervolt-loop.service.
```

**Comment by TartanSpartan** [comment]
Ok thanks for the clarification :) I'll close this ~~but then I need to raise a new issue because in spite of this progress, I'm still having trouble automating this process and having it be persistent.~~ and now actually it seems to be persisting and automating after reboots and sleeps. Many thanks for this utility!
