### ISSUE TITLE
Input/output error

### ISSUE THREAD

**Issue by ghost** [kitsunyan/intel-undervolt#54]
Using Ubuntu 20.04.1 LTS with 5.4.69-xanmod1 kernel. I have i5-2430M with Intel HD Graphics 3000.
```bash
v30xy@akaBedir:~/Masaüstü/undervolt$ sudo intel-undervolt apply
CPU (0): Input/output error
GPU (1): Input/output error
CPU Cache (2): Input/output error
System Agent (3): Input/output error
Analog I/O (4): Input/output error
```

**Comment by ghost** [comment]
Install command: `./configure --enable-systemd  && make && make install`

**Comment by regymm** [comment]
As far as I know, `intel-undervolt` doesn't support 2nd generation processors. Maybe [PHC](https://wiki.archlinux.org/index.php/PHC) can do this job?

**Comment by ghost** [comment]
Ok. Thanks for support.
