### ISSUE TITLE
"Failed to open memory device: Permission denied" After Upgrading to Fedora 34

### ISSUE THREAD

**Issue by rafidka** [kitsunyan/intel-undervolt#56]
Hi,

I upgraded to Fedora 34 yesterday and I started getting this error when I try to use `undervolt`:

```
Failed to open memory device: Permission denied
```

Any idea?

Thanks,
Rafid

**Comment by X-m7** [comment]
That's likely an issue with Fedora 34's new SELinux policy, not intel-undervolt. I filed a bug downstream [here](https://bugzilla.redhat.com/show_bug.cgi?id=1945955).

**Comment by andodet** [comment]
I am currently working on Fedora33 and this would be a deal-breaker to update, I really hope a solid workaround/approach will surface soon.

**Comment by rafidka** [comment]
@andodet , I have been using it for some time no with no issue; the original issue I reported is not showing anymore. I wonder whether it was just a temporary Kernel-related issue or something.

Closing the issue.

**Comment by andodet** [comment]
Thanks @rafidka for pointing this out, that's good news.
