### ISSUE TITLE
Error during Make 

### ISSUE THREAD

**Issue by virgiltu** [kitsunyan/intel-undervolt#8]
Hello I am running Ubuntu 18 but when I try to make this error comes up. Any ideas what causes it? When running make %% make install i get the same problem

`user@user-Link:~/intel-undervolt$ make
gcc -lm  -o intel-undervolt config.o main.o
main.o: In function `tdp_to_seconds':
main.c:(.text+0x4da): undefined reference to `exp2f'
main.o: In function `tdp_from_seconds':
main.c:(.text+0x515): undefined reference to `log2f'
main.c:(.text+0x58e): undefined reference to `log2f'
main.o: In function `tdp':
main.c:(.text+0x798): undefined reference to `exp2f'
main.c:(.text+0x7df): undefined reference to `exp2f'
collect2: error: ld returned 1 exit status
Makefile:18: recipe for target 'intel-undervolt' failed
make: *** [intel-undervolt] Error 1
`

Thank you

**Comment by rlshukhov** [comment]
Open Makefile and find:
`$(CC) -lm $(LDFLAGS) -o $@ $^`
then replace for:
`$(CC) $(LDFLAGS) -o $@ $^ -lm`

Save modified Makefile and try to `make %% make install`.
Profit :)

**Comment by kitsunyan** [comment]
Should be fixed by https://github.com/kitsunyan/intel-undervolt/pull/6
